### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Huangwei123-glitch** [wxguy/wrfplot#1]
Traceback (most recent call last):
  File "C:\PROGRA~1\wrfplot\wrfplot.py", line 361, in <module>
  File "C:\PROGRA~1\wrfplot\wrfplot.py", line 357, in main
  File "C:\PROGRA~1\wrfplot\wrfplot.py", line 168, in plot_variables
  File "C:\PROGRA~1\wrfplot\wrfplot.py", line 194, in get_time_period
  File "C:\PROGRA~1\wrfplot\xarray\core\common.py", line 176, in __iter__
TypeError: iteration over a 0-d arra

hello，An error occurred at run time，how can I fix it?

**Comment by wxguy** [comment]
Without providing detailed info, it would be very difficult to imagine what you are trying to do. How did you install? What days are you using? What command did you give? You have to provide more info.

**Comment by Huangwei123-glitch** [comment]
"wrfplot -h" was successfully executed.And The version was up to date
I entered the command line as follows:
wrfplot --input wrfout_d01_2016-10-06_03.nc --output ./ --vars "winds"

**Comment by Huangwei123-glitch** [comment]
![屏幕截图 2022-11-25 164050](https://user-images.githubusercontent.com/81974553/203937898-947d7f26-8c11-4381-98c9-d38a381973ce.jpg)
Hello, maybe there's something wrong with this code.
May be the data type of DataArray cannot be iterated directly.
I can't solve it. I hope you can help me, Thank you!

**Comment by wxguy** [comment]
I used the same command options you have tried. I got the below output in my terminal (windows 11):

![sample-plot](https://user-images.githubusercontent.com/9054645/203998199-4b7a4b3c-5f90-4edd-b85a-b0fd12b71501.png)

I presume that the application works fine. Please check your data file.

**Comment by mdidaaa** [comment]
Hello, I'm having the same issue. I installed version 0.9.3 via 

conda install -c cond-forge wrfplot 

on OSX Ventura with python@3.9. wrfplot --help, wrfplot --list-vars work succesfully
command line  

wrfplot --input wrfout_d01_2023-02-07_18:00:00 --output ./ --vars "rh2"   
(input file is output of WRF4.3.3) stops with

  File "/usr/local/anaconda3/lib/python3.9/site-packages/xarray/core/common.py", line 164, in __iter__
    raise TypeError("iteration over a 0-d array")
TypeError: iteration over a 0-d array

Any idea on how I can fix this? Thank you!

**Comment by wxguy** [comment]
Can you share a sample data (may be in compressed format). Or run the model for smaller domain and share the output file for testing. I have checked from my side with a few dataset and all working fine.

**Comment by mdidaaa** [comment]
Hello, 
You can try this dataset from the WRF tutorial as I did:
https://www2.mmm.ucar.edu/wrf/TUTORIAL_DATA/single_domain/wrfout_d01.tar.gz

wrfplot --input wrfout_d01_2016-10-07_00:00:00 --output ./ --vars rh2 

and I get the same output:

Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/site-packages/wrfplot/wrfplot.py", line 535, in main
    wrfplt.plot_variables()
  File "/usr/local/anaconda3/lib/python3.9/site-packages/wrfplot/wrfplot.py", line 200, in plot_variables
    self.get_time_period()
  File "/usr/local/anaconda3/lib/python3.9/site-packages/wrfplot/wrfplot.py", line 227, in get_time_period
    for _date in dates:
  File "/usr/local/anaconda3/lib/python3.9/site-packages/xarray/core/common.py", line 164, in __iter__
    raise TypeError("iteration over a 0-d array")
TypeError: iteration over a 0-d array

**Comment by wxguy** [comment]
https://github.com/wxguy/wrfplot/commit/2b64b45989007b2cb1d390e2721988ad0a74feb7 commit fixes the reported error. You ccan download the OS-specific binaries from https://github.com/wxguy/wrfplot/releases/tag/v0.9.4. The conda package will be available in short while. Closing the issue now.
