### ISSUE TITLE
wrfplot error linux

### ISSUE THREAD

**Issue by fipoucat** [wxguy/wrfplot#2]
I installed wrfplot on Ubuntu whch seems working, but when I run the command wrfplot --help I have a Fontconfig error:
 wrfplot --help
Fontconfig error: Cannot load default config file: No such file: (null)
usage: wrfplot [-h] [--list-vars] [--input <input_file>]
               [--output <output_dir>] [--vars <variables>]
               [--ulevels <upper-levels>] [--list-cmaps] [--cmap <cmap-name>]
               [--clevels <contour-levels>] [--dpi <value>] [--gif]
               [--gif-speed <seconds>] [--version]

Command line application to plot static WRF model prognostic products...

options:
  -h, --help            show this help message and exit
  --list-vars           Show list of variables supported by wrfplot and exit.
  --input <input_file>  Path to WRF generated netCDF.
  --output <output_dir>
                        Path to output directory for saving plotted images.
  --vars <variable(s)>  Name of the variable to be plotted. Multiple variables
                        are to be separated with ','. Use '--list-vars' option
                        to see list of supported variables.
  --ulevels <upper-levels>
                        Provide custom upper level(s) when plotting upper
                        atmospheric data. Each level is to be seperated by ','
                        i.e., '925,850,700'. Use '--list-vars' to know list of
                        supported upper level variables.
  --list-cmaps          List colour maps (cmaps) supported by wrfplot. Refer
                        https://pratiman-91.github.io/colormaps for
                        information on each colourmaps.
  --cmap <cmap-name>    Valid colormap name to fill colors. Use '--list-cmaps'
                        option to see list of supported colormaps. Must have
                        minimum 11 colors, else will lead to error.
  --clevels <contour-levels>
                        Provide custom contour level(s) to highlight data.
                        Levels are to be in ascending order and seperated by
                        ',' i.e., '24,26,28'. If single value is provided,
                        clevels will be automatically calculated.
  --dpi <value>         Increase or decrease the plotted image resolution.
                        Default is 125. More is higher resolution and less is
                        course resolution. Higher values will reduce the speed
                        of plot.
  --gif                 If applied, creates an animated GIF image. GIF image
                        will be saved same location as other images with a
                        name specifed in '--vars' option.
  --gif-speed <seconds>
                        Set speed of GIF frame in seconds. Default is 0.5 sec.
                        Lower value increases the speed of animation. To be
                        used with '--gif' option to take effect.
  --version             Print version information of application and exit.

© J Sundar, wrf.guy@gmail.com, 2023
What does this mean and any hint to solve it?

**Comment by wxguy** [comment]
This is actually a warning. Did you try to plot with actual data?

**Comment by fipoucat** [comment]
Ok, you are right, I tested rh2 plot with success.
Great

**Comment by fipoucat** [comment]
I am working in an extreme event and wonder if there is an exaplample of rainc+rainnc plot to highlith intensity of the event?

Thank you

**Comment by wxguy** [comment]
`ppn_accum` is the variable you are looking for.

**Comment by fipoucat** [comment]
Ok, thanks for the clarification.
