### ISSUE TITLE
error for certain variables

### ISSUE THREAD

**Issue by fipoucat** [wxguy/wrfplot#3]
I tested some variables with success but get errors for some others:

wrfplot --input wrfout_d01-06.nc --vars "mid_cloudfrac" --output ~/Documents/wrfplot_output
Fontconfig error: Cannot load default config file: No such file: (null)
                                                                                
*** Initialising plotting for variable : "mid_cloudfrac" ***

        Plotting "mid_cloudfrac" for Time: 06-01-2002_00:00                     
invalid literal for int() with base 10: 'auto'                                  
Traceback (most recent call last):     

is there any prior step before being able to plot these variables?

**Comment by fipoucat** [comment]
still can't solve this I anotice for many other variables. Any planed fix?

**Comment by wxguy** [comment]
> still can't solve this I anotice for many other variables. Any planed fix?

Thanks for reporting. The latest version has fixed many bugs apart from this one. Closing this issue as I am not able to produce with latest version. 

Please open a new issue if you face any problem with the latest release.
