### ISSUE TITLE
Wind barbs are incorrect for Southern Hemisphere

### ISSUE THREAD

**Issue by GregJWilliams** [wxguy/wrfplot#4]
Great tool, but note that wind barbs are plotted in Northern Hemisphere form only - and are therefore incorrect for Southern Hemisphere coverages.

Including a commendline arg to switch flag direction would work for some use cases, but not for coverages that span North and South of the equator.

**Comment by wxguy** [comment]
Oh. never thought about it. My testing was always on NH data. Will look into the issue.

**Comment by wxguy** [comment]
You can try the latest version which solves this issue. In addition, the speed of the plotting is now greatly improved.
